# for reasons I can't figure out, spring boot/junit/mockito seems to need a file in the test/resources folder named "application.properties" to properly find the right properties files for test port and database settings and actually use them.
server.port:9085

server.error.include-stacktrace=never
